[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "precon3d"
authors = [
    { email = "pchao@sandia.gov", name = "Paul Chao" },
    { email = "apolon@sandia.gov", name = "Andrew Polonsky" },
]
description = "(PRE)pare serial sectioning montage data for (RECON)struction in (3D)"
readme = "README.md"
requires-python = ">=3.11, <=3.12.1"
dependencies = [
    'czifile>=2019.7.2.1',  # Required for reading CZI files.
    'aicsimageio==4.14.0',  # High-level image I/O library.
    'numpy==1.26.3',        # Core numerical library.
    'scikit-image>=0.25.2', # Image processing library.
    'Pillow>=11.3.0',       # Image manipulation library.
    'pyyaml>=6.0.2',        # YAML configuration parsing.
    'typer>=0.17.4',        # CLI tool.
    "rich>=14.1.0",         # Enhanced terminal output.
    "aicspylibczi==3.1.2",
    "napari>=0.6.4",
    "scikit-learn>=1.7.2",
    "pystackreg==0.2.8",
    "seaborn==0.12.2",      # Statistical data visualization library.
    "pytz",
]
version = '1.0.2'
[project.optional-dependencies]

dev = [
    "black",
    "flake8",
    "pdbp",
    "pytest==8.3.3",
    "pytest-cov==5.0.0",
    "mkdocs",
    "mkdocs-material",
    "pdoc",
]

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning:czifile.*"]

[project.urls]
documentation = "https://sandialabs.github.io/precon3d/docs/userguide/book/index.html"
repository = "https://github.com/sandialabs/precon3d"

# CLI Entry Points
[project.scripts]
precon3d = "precon3d.main:app"
